"""45 — The Fine Structure Constant: α = 1/(43π + ln7)"""
from crystal_topos import d_total, beta0
import math
print("The Fine Structure Constant")
print("=" * 55)
D = d_total(); b = beta0()
alpha_inv = (D + 1) * math.pi + math.log(b)
print(f"  α⁻¹ = (D+1)π + ln β₀")
print(f"       = ({D}+1)π + ln {b}")
print(f"       = {D+1}π + ln {b}")
print(f"       = {(D+1)*math.pi:.6f} + {math.log(b):.6f}")
print(f"       = {alpha_inv:.6f}")
print(f"  CODATA: 137.035999")
print(f"  PWI:    {abs(alpha_inv - 137.035999)/137.035999 * 100:.4f}%")
print(f"\n  Every integer:")
print(f"    D + 1 = 43 = Σd + χ + 1 = 36 + 6 + 1")
print(f"    β₀ = 7 = (11×3 - 2×6)/3")
print(f"    All from N_w=2, N_c=3.")
print(f"\n  Feynman: 'One of the greatest damn mysteries in physics.'")
print(f"  Crystal: 43π + ln 7. Mystery solved.")
