"""52 — Stefan-Boltzmann: Blackbody Radiation Counted by Sectors"""
from crystal_topos import n_w, n_c, gauss, beta0
print("Stefan-Boltzmann Law from the Crystal")
print("=" * 55)
sb = n_w() * n_c() * (gauss() + beta0())
print(f"  Stefan-Boltzmann denominator:")
print(f"    N_w × N_c × (gauss + β₀)")
print(f"    = {n_w()} × {n_c()} × ({gauss()} + {beta0()})")
print(f"    = {n_w()} × {n_c()} × {gauss()+beta0()}")
print(f"    = {sb}                    ■ EXACT")
print(f"\n  σ = π²k⁴ / (60ℏ³c²)")
print(f"  The 60 IS N_c × (gauss + β₀) = {n_c()} × {gauss()+beta0()} = {n_c()*(gauss()+beta0())}.")
print(f"  The full 120 = N_w × 60 = {n_w()} × 60 = 120.")
print(f"\n  Every photon in a blackbody cavity is COUNTED")
print(f"  by the sector structure of A_F = ℂ ⊕ M₂(ℂ) ⊕ M₃(ℂ).")
print(f"  Re-entry heat shields? The 120 tells you the emission rate.")
