"""75 — Metallic Hydrogen: Lattice Phase Transition"""
from crystal_topos import n_w, n_c, chi, d_total
import math
print("Metallic Hydrogen from Lattice Tension")
print("=" * 55)
print(f"  Normal hydrogen: electron in s-orbital (singlet sector)")
print(f"  Eigenvalue: λ = 1 (singlet)")
print(f"\n  Under pressure: electron forced from singlet → weak sector")
print(f"  Eigenvalue: λ = 1 → 1/N_w = 1/{n_w()}")
print(f"  Energy gap: ΔE = ln(N_w) = ln({n_w()}) = {math.log(n_w()):.4f}")
print(f"\n  Metallic transition occurs when:")
print(f"  Pressure × Volume ≥ ΔE per atom")
print(f"  P × a₀³ ≥ ln(N_w) × Rydberg")
print(f"\n  In the Heyting order:")
print(f"  Insulator: all electrons in singlet (λ = 1)")
print(f"  Metal: electrons in weak sector (λ = 1/{n_w()})")
print(f"  The transition IS a sector crossing.")
print(f"\n  Jupiter's core: P ≈ 500 GPa → metallic H")
print(f"  The crystal says: the transition happens when the")
print(f"  lattice tension exceeds the singlet-weak gap.")
print(f"  No billion-dollar experiment needed.")
print(f"  Just compute: P_c = ln({n_w()}) × Ry / a₀³ from α and m_e.")
