"""80 — Why Electrons Can't Hit Atoms in a Superconductor"""
from crystal_topos import n_w, n_c, chi, sigma_d
print("Type-Safe Electron Flow")
print("=" * 55)
print(f"  In Haskell:")
print(f"    A type error means the program can't compile.")
print(f"    You CANNOT pass a String where an Int is expected.")
print(f"\n  In the Crystal:")
print(f"    A scattering event means sectors mismatch.")
print(f"    You CANNOT scatter singlet off singlet.")
print(f"\n  Normal conductor:")
print(f"    Electron sector: λ = 1/N_w = 1/{n_w()} (weak)")
print(f"    Lattice sector:  λ = 1 (singlet)")
print(f"    1/{n_w()} ≠ 1 → type mismatch → SCATTERING ALLOWED")
print(f"\n  Superconductor:")
print(f"    Cooper pair sector: λ = 1 (singlet)")
print(f"    Lattice sector:     λ = 1 (singlet)")
print(f"    1 = 1 → type match → SCATTERING FORBIDDEN")
print(f"\n  The Heyting algebra enforces this:")
print(f"    Scattering requires λ_electron ≠ λ_lattice")
print(f"    For Cooper pair: 1 ≠ 1 is FALSE")
print(f"    The geometry REJECTS the collision")
print(f"    Electron flow is TYPE-SAFE")
print(f"\n  Σd/χ² = {sigma_d()}/{chi()**2} = {sigma_d()//chi()**2}")
print(f"  This is why: sector sum = channel² = perfect impedance.")
print(f"  No reflection. No friction. No resistance.")
