"""81 — The Arrow of Time is a Type Constraint"""
from crystal_topos import QuantumState, chi, crystal_max_entropy, n_w, n_c
import math
print("The Arrow of Time from Heyting Logic")
print("=" * 60)
S = crystal_max_entropy()
print(f"  ENTROPY PER STEP:")
print(f"    ΔS = ln(χ) = ln({chi()}) = {S:.4f} nats")
print(f"    = {S/math.log(2):.4f} bits per compression step")
print(f"\n  WHY TIME IS IRREVERSIBLE:")
print(f"    The compression functor S: End(A_F) → End(A_F)")
print(f"    maps 650 endomorphisms to fewer.")
print(f"    S is a FUNCTOR, not an isomorphism.")
print(f"    S ∘ S⁻¹ ≠ Id. No inverse exists.")
print(f"\n  IN HEYTING LOGIC:")
print(f"    ¬¬x ≠ x (double negation ≠ identity)")
print(f"    NOT(NOT(past)) ≠ past")
print(f"    You cannot undo a measurement.")
print(f"    You cannot un-live a moment.")
print(f"    The arrow of time IS intuitionistic logic.")
print(f"\n  IN HASKELL:")
print(f"    IO a → IO a (side effects are one-way)")
print(f"    You can't un-print to stdout.")
print(f"    The IO monad IS the arrow of time.")
print(f"    Time irreversibility = type constraint.")
print(f"\n  PROOF:")
psi = QuantumState.max_entangled()
print(f"    S_entanglement = {psi.entanglement_entropy():.4f} = ln({chi()})")
print(f"    ΔS_arrow       = {S:.4f} = ln({chi()})")
print(f"    Same number. Entanglement = irreversibility.")
print(f"    Both = ln(χ). Both from χ = {n_w()} × {n_c()} = {chi()}.")
